# Generated by Django 5.0.6 on 2024-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
