services:
  community:
    image: ccs/community-leaderboard:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./logs/:/app/logs/
    restart: always
    env_file:
      - .env
    networks:
      - db

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A app.celery worker --loglevel=WARNING
    depends_on:
      - community
      - redis
    restart: always
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A app.celery beat --loglevel=WARNING
    depends_on:
      - community
      - redis
    restart: always
    env_file:
      - .env

  redis:
    image: redis:7

  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XXOs1e7|r_i|LQqs
      POSTGRES_DB: community_db
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - db

volumes:
  postgres_data:

networks:
  db:
    driver: bridge
