[tool.poetry]
name = "codeboard"
version = "0.1.0"
description = ""
authors = ["CCS <ccs@thapar.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"

adrf = "*"
aiohappyeyeballs = "*"
aiohttp = "*"
aiosignal = "*"
amqp = "*"
asgiref = "*"
async-property = "*"
attrs = "*"
billiard = "*"
celery = "*"
certifi = "*"
charset-normalizer = "*"
click = "*"
click-didyoumean = "*"
click-plugins = "*"
click-repl = "*"
cron_descriptor = "*"
Django = "*"
django-celery-beat = "*"
django-cors-headers = "*"
django-timezone-field = "*"
django_celery_results = "*"
djangorestframework = "*"
djangorestframework_simplejwt = "*"
frozenlist = "*"
gunicorn = "*"
h11 = "*"
idna = "*"
kombu = "*"
multidict = "*"
packaging = "*"
propcache = "*"
psycopg2-binary = "*"
PyJWT = "*"
python-crontab = "*"
python-dateutil = "*"
python-dotenv = "*"
redis = "*"
requests = "*"
six = "*"
sqlparse = "*"
typing_extensions = "*"
tzdata = "*"
urllib3 = "*"
uvicorn = "*"
vine = "*"
wcwidth = "*"
yarl = "*"

[tool.poetry.group.dev.dependencies]
django-stubs = "*"
django-stubs-ext = "*"
djangorestframework-stubs = "*"
mypy = "*"
mypy_extensions = "*"
pathspec = "*"
prompt_toolkit = "*"
types-PyYAML = "*"
types-requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
