# Generated by Django 5.0.6 on 2024-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('position', models.CharField(choices=[('MB', 'Member'), ('CR', 'Core'), ('JS', 'Joint Secretary'), ('FS', 'Finance Secretary'), ('GS', 'General Secretary')], default='MB', max_length=2)),
                ('roll_no', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
