# Generated by Django 5.2.6 on 2025-09-14 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "leaderboard_key",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "leaderboard_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_key", models.AutoField(primary_key=True, serialize=False)),
                ("leetcode_id", models.IntegerField(db_index=True, default=0)),
                ("title", models.CharField(default="", max_length=100)),
                (
                    "titleSlug",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                (
                    "questionDate",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leetcode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        db_index=True, default="", max_length=100, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Scraping..", max_length=100, null=True
                    ),
                ),
                (
                    "leetcode_rank",
                    models.CharField(
                        blank=True, default="Scraping..", max_length=10, null=True
                    ),
                ),
                ("daily_rank", models.IntegerField(blank=True, default=0, null=True)),
                ("weekly_rank", models.IntegerField(blank=True, default=0, null=True)),
                ("monthly_rank", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "photo_url",
                    models.CharField(
                        blank=True, default="Scarping..", max_length=200, null=True
                    ),
                ),
                ("total_solved", models.IntegerField(blank=True, default=0, null=True)),
                ("matched_ques", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "submission_dict",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "total_solved_dict",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "matched_ques_dict",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("day", "day"), ("week", "week"), ("month", "month")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("questions_solved", models.IntegerField(default=0)),
                ("earliest_solved_timestamp", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaderboard.leetcode",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "interval")},
            },
        ),
    ]
