# Generated by Django 5.0.7 on 2024-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_usernamechangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_key',
        ),
        migrations.AlterField(
            model_name='question',
            name='leetcode_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
