# Generated by Django 5.0.7 on 2024-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_remove_question_question_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='leetcode_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
