# Generated by Django 5.0.7 on 2024-10-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_question_leetcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Basic', max_length=20),
        ),
    ]
