# Generated by Django 5.0.7 on 2024-07-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs_auth', '0003_alter_cuser_is_admin_alter_cuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
