# Generated by Django 5.0.7 on 2024-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs_auth', '0004_cuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
