# Generated by Django 5.0.7 on 2024-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs_auth', '0005_alter_cuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='admin_password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
