# Generated by Django 5.0.7 on 2024-10-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccs_auth', '0006_cuser_admin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuser',
            old_name='admin_password',
            new_name='login_password',
        ),
    ]
