# Generated by Django 5.0.6 on 2024-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_leaderboardentry_earliest_solved_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboard_key', models.AutoField(primary_key=True, serialize=False)),
                ('leaderboard_type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=20)),
                ('leaderboard_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='daily_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='monthly_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='weekly_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
