# Generated by Django 5.0.6 on 2024-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_profile_question_usersolvedquestion_leetcodedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leetcode_acc',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('leetcode_name', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='Scraping..', max_length=100, null=True)),
                ('rank', models.CharField(blank=True, default='Scraping..', max_length=10, null=True)),
                ('photo_url', models.CharField(blank=True, default='Scarping..', max_length=200, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, default=0, null=True)),
                ('last_solved', models.CharField(blank=True, default='Scraping..', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='codechefdata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='codechefdata',
            name='solved_questions',
        ),
        migrations.RemoveField(
            model_name='codeforcesdata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='codeforcesdata',
            name='solved_questions',
        ),
        migrations.RemoveField(
            model_name='leetcodedata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='leetcodedata',
            name='solved_questions',
        ),
        migrations.DeleteModel(
            name='LeetCodeUser',
        ),
        migrations.RemoveField(
            model_name='usersolvedquestion',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='usersolvedquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='CodeChefData',
        ),
        migrations.DeleteModel(
            name='CodeforcesData',
        ),
        migrations.DeleteModel(
            name='LeetCodeData',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserSolvedQuestion',
        ),
    ]
