# Generated by Django 5.0.6 on 2024-06-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_leetcode_acc_remove_codechefdata_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('title', models.CharField(default='', max_length=100, unique=True)),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('platform', models.CharField(choices=[('LeetCode', 'LeetCode'), ('Codeforces', 'Codeforces'), ('CodeChef', 'CodeChef')], default='LeetCode', max_length=50)),
                ('platform_id', models.CharField(blank=True, default='', help_text='Enter the question id from the platform', max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='matching_questions',
            field=models.ManyToManyField(blank=True, related_name='matching_to', to='leaderboard.questions'),
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='leaderboard.questions'),
        ),
    ]
