# Generated by Django 5.0.6 on 2024-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_questions_leetcode_acc_matching_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('titleSlug', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='leetcode_acc',
            name='matching_questions',
        ),
        migrations.RemoveField(
            model_name='leetcode_acc',
            name='solved_questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('titleSlug', models.CharField(default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('SolvedBy', models.ManyToManyField(blank=True, to='leaderboard.leetcode_acc')),
            ],
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='SolvedQuestions',
            field=models.ManyToManyField(blank=True, to='leaderboard.solvedquestion'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
