# Generated by Django 5.0.6 on 2024-06-10 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_solvedquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcode_acc',
            name='SolvedQuestions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='SolvedBy',
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='MatchedQuestions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(unique=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='question',
            name='leetcode_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SolvedQuestion',
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='SolvedQuestions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(unique=True), blank=True, default=list, size=None),
        ),
    ]
