# Generated by Django 5.0.6 on 2024-06-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_remove_leetcode_acc_solvedquestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcode_acc',
            name='last_solved',
        ),
    ]
