# Generated by Django 5.0.6 on 2024-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_remove_leetcode_acc_last_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='question_key',
        ),
    ]
