# Generated by Django 5.0.6 on 2024-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_rename_question_id_question_question_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leetcode_acc',
            old_name='number_of_questions',
            new_name='matched_ques',
        ),
        migrations.RenameField(
            model_name='leetcode_acc',
            old_name='MatchedQuestions',
            new_name='matched_ques_list',
        ),
        migrations.RenameField(
            model_name='leetcode_acc',
            old_name='SolvedQuestions',
            new_name='total_solved_list',
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='total_solved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
