# Generated by Django 5.0.6 on 2024-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_rename_number_of_questions_leetcode_acc_matched_ques_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leetcode_acc',
            old_name='rank',
            new_name='leetcode_rank',
        ),
        migrations.AddField(
            model_name='leetcode_acc',
            name='ccs_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
