# Generated by Django 5.0.6 on 2024-06-13 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_rename_rank_leetcode_acc_leetcode_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionDate',
            field=models.DateField(default=datetime.date(2024, 6, 13)),
        ),
    ]
