# Generated by Django 5.0.6 on 2024-06-14 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_question_questiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
