# Generated by Django 5.0.6 on 2024-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_alter_question_questiondate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leetcode_acc',
            old_name='leetcode_name',
            new_name='username',
        ),
    ]
