POST http://127.0.0.1:8000/auth/signup/
Content-Type: application/json

{ "username": "ishan2", "password": "admin" }

###

POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
  "username": "ishan2",
  "password": "admin"
}

###

GET http://127.0.0.1:8000/auth/test_token/
Content-Type: application/json
Authorization: Token 6edc046885ca1e1dc4c1bc20f1743b70f3e5a5bd

{}

###
POST http://127.0.0.1:8000/auth/signup_token/
Content-Type: application/json

{ "name": "test", "email":"test@ccs.com", "password": "1234", "is_superuser": false}

###

POST http://127.0.0.1:8000/auth/login_token/
Content-Type: application/json

{"token": "xx", "name": "test", "email":"test@ccs.com", "password": "1234"}

###

GET http://127.0.0.1:8000/auth/logout/
Content-Type: application/json
Authorization: Token 7acb1878fae9e7485fc67794feb86ff41df0d6b9

{}