# Generated by Django 5.0.6 on 2024-06-23 20:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboard_key', models.AutoField(primary_key=True, serialize=False)),
                ('leaderboard_type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=20)),
                ('leaderboard_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_key', models.AutoField(primary_key=True, serialize=False)),
                ('leetcode_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('titleSlug', models.CharField(default='', max_length=100)),
                ('questionDate', models.DateTimeField(default=datetime.datetime.now)),
                ('difficulty', models.CharField(choices=[('Basic', 'Basic'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced')], default='Basic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leetcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='Scraping..', max_length=100, null=True)),
                ('leetcode_rank', models.CharField(blank=True, default='Scraping..', max_length=10, null=True)),
                ('daily_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('weekly_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('monthly_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('photo_url', models.CharField(blank=True, default='Scarping..', max_length=200, null=True)),
                ('total_solved', models.IntegerField(blank=True, default=0, null=True)),
                ('matched_ques', models.IntegerField(blank=True, default=0, null=True)),
                ('submission_dict', models.JSONField(blank=True, default=dict, null=True)),
                ('total_solved_dict', models.JSONField(blank=True, default=dict, null=True)),
                ('matched_ques_dict', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=10)),
                ('questions_solved', models.IntegerField(default=0)),
                ('earliest_solved_timestamp', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.leetcode')),
            ],
            options={
                'unique_together': {('user', 'interval')},
            },
        ),
    ]
